### ISSUE TITLE
No worky does, fix plese

### ISSUE THREAD

**Issue by SienceMC** [SilvanKohler/MS-Paint-shit-edition#3]
**Describe the bug**
NO WORK

**To Reproduce**
1. Download
2. Install Requirements
3. Start
4. See Error.

**Expected behavior**
FUCKING START

**Error**
```
 ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
Traceback (most recent call last):
  File "......\MS-Paint-shit-edition-master\paint.py", line 7, in <module>
    import numpy as np
  File ".........\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\__init__.py", line 305, in <module>
    _win_os_check()
  File "........\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
    raise RuntimeError(msg.format(__file__)) from None
RuntimeError: The current Numpy installation ('.......\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
```

**Desktop (please complete the following information):**
OS: Windows 10 2004
Version: newest shit

**Comment by SienceMC** [comment]
FAST AS FUCK BOYYYYYYYYY

**Comment by SilvanKohler** [comment]
Please run this in the python console:

```
import sys
print("Python version")
print (sys.version)
print("Version info.")
print (sys.version_info)
```
Are you running it with native python?

**Comment by SienceMC** [comment]
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print("Python version")
Python version
>>> print (sys.version)
3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]
>>> print("Version info.")
Version info.
>>> print (sys.version_info)
sys.version_info(major=3, minor=8, micro=0, releaselevel='final', serial=0)
>>>

**Comment by SilvanKohler** [comment]
Please show me the output of:
`python -m pip show numpy`

**Comment by SienceMC** [comment]
Name: numpy
Version: 1.19.4
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: c:\users\....\appdata\local\programs\python\python38\lib\site-packages
Requires:
Required-by:

**Comment by SilvanKohler** [comment]
Ok, so run:
`pip install numpy==1.19.3`
It should work now.

**Comment by SienceMC** [comment]
It starts but drawing doesn't actually work: Exception in thread Thread-2:
```
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Users\....\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
  File "paint.py", line 139, in <module>
    mainprocess.run()
    self.run()
  File "paint.py", line 105, in run
  File "paint.py", line 51, in run
    positioningQAB.rect = rect
NameError: name 'positioningQAB' is not defined
    QAB.process.communicate((self.rect.left, self.rect.top - settings['quickAccessBarWindowSize']['heigth']))
AttributeError: 'NoneType' object has no attribute 'communicate'
```

**Comment by SilvanKohler** [comment]
I think we done here

**Comment by SienceMC** [comment]
Opened a new issue for error in last message.
